name: CI/CD Pipeline

# Trigger the pipeline on push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx (to build multi-platform images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to Docker Hub (hardcode username and password)
      - name: Log in to Docker Hub
        run: |
          echo "Toothpaste" | docker login -u "antaratalapatra" --password-stdin

      # Build and push the Docker image to Docker Hub with the 'latest' tag
      - name: Build and push Docker image
        run: |
          docker build -t antaratalapatra/react-vite-app:latest .
          docker push antaratalapatra/react-vite-app:latest
